config/routes.rb
Womo::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'
  match 'dashboard' => "home#dashboard" , :as => :dashboard
  
  resources :projects  do 
    resources :pictures 
  end
  resources :bookmarks 
  
  devise_scope :user do
    get "admin", :to => "devise/sessions#new"
  end
  
  # uploading assembly_url to project  # if the processing is done in the server. 
  match 'create_picture_from_assembly/:project_id' => "pictures#create_picture_from_assembly", :as => :create_picture_from_assembly, :method => :post
  match 'transloadit_status_for_picture' => "pictures#transloadit_status_for_picture", :as => :transloadit_status_for_picture, :method => :post
  match 'new_uploaded_picture_display/:picture_id' => "pictures#new_uploaded_picture_display", :as => :new_uploaded_picture_display
  
  
  
  # edit project content: title, teaser, story/description, :featured status , upload featured image
  match 'edit_project_content/:project_id' => "projects#edit_project_content", :as => :edit_project_content
  match 'update_project_content/:project_id' => "projects#update_project_content", :as => :update_project_content, :method => :post 
  
  # manage featured project ( appears in the front page )
  match 'manage_featured_project/:project_id' => "projects#manage_featured_project", :as => :manage_featured_project
  match 'create_featured_picture/:project_id' => 'pictures#create_featured_picture',  :as => :create_featured_picture, :method => :post 
  
  # picture 
  match 'destroy_picture' => 'pictures#destroy_picture', :as => :destroy_picture, :method => :post 
  match 'switch_teaser' => "pictures#switch_teaser", :as => :switch_teaser, :method => :post 
  
  match 'switch_featured' => "pictures#switch_featured", :as => :switch_featured, :method => :post 
  
  match 'publish' => 'projects#publish', :as => :publish, :method => :post 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:index]
  def index
    @projects = Project.where(:is_published => true ).order("first_publication_datetime DESC")
    @featured_projects = Project.where(:is_featured_project => true).limit(4).order("first_publication_datetime DESC")
    
    # render :layout => "front_page" 
    render :layout => "front_page"  , :file => 'home/front_page/index'
  end
  
  def dashboard
    redirect_to deduce_after_sign_in_url
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dashboard_page_content.html.erb
<section class="span9 alignright testimonials" id="content"> 
  <div class='span9' style="margin-left:0; margin-bottom:30px;">
    <div> 
      <a class="btn btn-success btn-large">
        <i class="icon-plus icon-white"></i>
        Create Project
      </a>
    </div>
    
    <br />
    
    <%= render :partial => "projects/new_object_form", :locals => {
      :new_object => Project.new,
      :url => projects_url 
    }%>
    
    
  </div>
    
    
    

    
     

  <% array = [
    {
      :pic => 'http://cheesenclick.com/wp-content/uploads/2012/06/DSC_0220(pp_w900_h599).jpg',
      :teaser => "Perfection is in the eyes of God."
    },
    {
      :pic => 'http://www.menaralighthouse.com/images/article/000_MG_3455-01.jpg___4GK8r2uRZCAdduhSdEDz.jpg',
      :teaser => "markus+pamela!



      It is a love story between Jakarta and Bandung, Markus lives in Jakarta while Pam in Bandung. here is the interesting story, they almost finished their wedding preparation but suddenly they wanted us to do their prewedding photo. The prewedding itself is a representation of how they have been dating so far. The aeroplane scene was a phase where they did the long-distance relationship. Actually we wanted to do the session in airport, but due to complex bureaucracy we chose another option.



      We can't avoid social media nowadays, neither they did. Markus sent a message via Facebook to Pamela and from there everything was begun. Surprisingly, they still keep the message, we think it is like a souvenir in their relationship. At the day of prewedding session, we need to travel quite far from one place to another, the weather and sunshine were too harsh at afternoon, so we waited around 4 PM and found out dark clouds :O everywhere. We used that situation to accentuate the clouds dramatically! Really love the aeroplane scene...



      Hey lover, keep going!

      "
    },
    {
      :pic => 'http://www.monopictura.com/blog/wp-content/uploads/2012/08/mono-w-sansri-05.jpg',
      :teaser => 'test'
    },
    {
      :pic => 'http://www.foreachlove.com/wp-content/uploads/2012/08/0001.jpg',
      :teaser => 'test'
    }  
  ]%>
   
   
  <% projects.each do |project| %>
    <%= render :partial => "projects/project_dashboard_entry", :locals => {
      :project => project
    } %>
  <% end %> 
   
  
  <% array.each do |element| %>
    <article class='row'> 
      <div class='span6'>
        <%= image_tag element[:pic] %>
      </div>
      <div class='span3'>
        <%=  element[:teaser]%>
      </div>
    </article>
  <% end %> 
  
   
 
</section>

app/views/home/_fake_home.html.erb
<% array = [
  {
    :pic => 'http://cheesenclick.com/wp-content/uploads/2012/06/DSC_0220(pp_w900_h599).jpg',
    :teaser => "Perfection is in the eyes of God."
  },
  {
    :pic => 'http://www.menaralighthouse.com/images/article/000_MG_3455-01.jpg___4GK8r2uRZCAdduhSdEDz.jpg',
    :teaser => "markus+pamela!



    It is a love story between Jakarta and Bandung, Markus lives in Jakarta while Pam in Bandung. here is the interesting story, they almost finished their wedding preparation but suddenly they wanted us to do their prewedding photo. The prewedding itself is a representation of how they have been dating so far. The aeroplane scene was a phase where they did the long-distance relationship. Actually we wanted to do the session in airport, but due to complex bureaucracy we chose another option.



    We can't avoid social media nowadays, neither they did. Markus sent a message via Facebook to Pamela and from there everything was begun. Surprisingly, they still keep the message, we think it is like a souvenir in their relationship. At the day of prewedding session, we need to travel quite far from one place to another, the weather and sunshine were too harsh at afternoon, so we waited around 4 PM and found out dark clouds :O everywhere. We used that situation to accentuate the clouds dramatically! Really love the aeroplane scene...



    Hey lover, keep going!

    "
  },
  {
    :pic => 'http://www.monopictura.com/blog/wp-content/uploads/2012/08/mono-w-sansri-05.jpg',
    :teaser => ''
  },
  {
    :pic => 'http://www.foreachlove.com/wp-content/uploads/2012/08/0001.jpg',
    :teaser => ''
  }  
]%>

 <% array.each do |element| %>
 
    <div class="row portfolio-single entry" style='margin-bottom:30px;'>

        <!-- .span8 -->
        <div class="span8" style="text-align:center;"> 
             <img src="<%= element[:pic] %>" />
        </div><!-- /.span8 -->

        <!-- .span4 -->
        <div class="span4"> 
            <h1>Lorem ipsum dolor</h1>
            <p><%= element[:teaser] %></p>
            
            <ul class="clearfix skilss" data-rel="tooltip" title="Services Use">
                <li><i class="icon-ok-circle"></i>Web Design</li>
                <li><i class="icon-ok-circle"></i>jQuery</li>
                <li><i class="icon-ok-circle"></i>Wordpress</li>
                <li><i class="icon-ok-circle"></i>PHP</li>
            </ul>

            <a href="#" class="btn btn-danger btn-large"><i class="icon-map-marker icon-white"></i>Launch website</a>

        </div><!-- /.span4 -->

    </div><!-- /.row --> 
  <% end %>

app/views/home/_real_home.html.erb
 <% @projects.each do |project| %>
 
    <div class="row portfolio-single entry" style='margin-bottom:30px;'>

        <!-- .span8 -->
        <div class="span8" style="text-align:center;"> 
             <%= image_tag project.main_picture.index_image_url %>
        </div><!-- /.span8 -->

        <!-- .span4 -->
        <div class="span4"> 
            <h1><%= link_to project.title, project_url(project) %></h1> 
            <div class='project-description'> 
              <%=  project.description[0..150] + "..." %>  
            </div>
            
            <ul class="clearfix skilss" data-rel="tooltip" title="Services Use">
                <li><i class="icon-ok-circle"></i>Web Design</li>
                <li><i class="icon-ok-circle"></i>jQuery</li>
                <li><i class="icon-ok-circle"></i>Wordpress</li>
                <li><i class="icon-ok-circle"></i>PHP</li>
            </ul>

            <a href="#" class="btn btn-danger btn-large"><i class="icon-map-marker icon-white"></i>Launch website</a>

        </div><!-- /.span4 -->

    </div><!-- /.row --> 
  <% end %>

app/views/home/dashboard.html.erb
<%= render :partial => "layouts/guide" %> 


<div class="row">
  <!-- render the page -->
  <%= render :partial => "home/dashboard_page_content" %> 
  <!-- render the process list -->
  <%= render :partial => 'layouts/process_nav'%>
</div>

app/views/home/index.html.erb
  
  <%#= render :partial => "home/fake_home" %>
  <%= render :partial => "home/real_home"%>