config/routes.rb
Womo::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'
  match 'dashboard' => "home#dashboard" , :as => :dashboard
  
  resources :projects  do 
    resources :pictures 
  end
  resources :bookmarks 
  
  devise_scope :user do
    get "admin", :to => "devise/sessions#new"
  end
  
  # uploading assembly_url to project  # if the processing is done in the server. 
  match 'create_picture_from_assembly/:project_id' => "pictures#create_picture_from_assembly", :as => :create_picture_from_assembly, :method => :post
  match 'transloadit_status_for_picture' => "pictures#transloadit_status_for_picture", :as => :transloadit_status_for_picture, :method => :post
  match 'new_uploaded_picture_display/:picture_id' => "pictures#new_uploaded_picture_display", :as => :new_uploaded_picture_display
  
  
  
  # edit project content: title, teaser, story/description, :featured status , upload featured image
  match 'edit_project_content/:project_id' => "projects#edit_project_content", :as => :edit_project_content
  match 'update_project_content/:project_id' => "projects#update_project_content", :as => :update_project_content, :method => :post 
  
  # manage featured project ( appears in the front page )
  match 'manage_featured_project/:project_id' => "projects#manage_featured_project", :as => :manage_featured_project
  match 'create_featured_picture/:project_id' => 'pictures#create_featured_picture',  :as => :create_featured_picture, :method => :post 
  
  # picture 
  match 'destroy_picture' => 'pictures#destroy_picture', :as => :destroy_picture, :method => :post 
  match 'switch_teaser' => "pictures#switch_teaser", :as => :switch_teaser, :method => :post 
  
  match 'switch_featured' => "pictures#switch_featured", :as => :switch_featured, :method => :post 
  
  match 'publish' => 'projects#publish', :as => :publish, :method => :post 
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title , use: :slugged
  
  attr_accessible :title, :teaser, :description
  has_many :pictures
  
  validates_presence_of :title 
  belongs_to :category
  
  
  
=begin
  Object Creation
=end
  def self.create_object( current_user, object_params )  
    new_object = self.new object_params 
    if not current_user.has_role?(:vendor) 
      return new_object 
    end
    new_object.user_id = current_user.id 
    new_object.save 

    return new_object
  end
  
  def update_object( current_user, object_params )    
    self.assign_attributes( object_params ) 
    if not current_user.has_role?(:vendor) 
      return self 
    end
     
    if self.title.nil? or self.title.length == 0 
      self.errors.add(:title , "The title can't be empty" ) 
      return self 
    end
    self.save 
    
    

    return self
  end
  
  
  
  def Project.latest_available_projects
    Project.where(:is_deleted => false ).order("created_at DESC")
  end
  
  def main_picture   # the teaser picture 
    main_picture = self.pictures.where(:is_deleted => false, :is_feature_picture => false , :is_main_picture => true ).first
    if main_picture.nil?
      main_picture=   self.pictures.where(:is_deleted => false , :is_feature_picture => false ).first
    end 
    
    return main_picture
  end
  
  
  
  
=begin
  Article management
=end
  def current_main_pictures # teaser 
    self.pictures.where(:is_deleted => false,:is_feature_picture => false, :is_main_picture => true).order("name ASC")
  end
  
  def content_pictures
    self.pictures.where(:is_deleted => false,:is_feature_picture => false ).order("name ASC")
  end
  
  def featured_pictures
    self.pictures.where(:is_deleted => false,:is_feature_picture => true , :is_feature_picture_displayed => false ).order("name ASC")
  end
  
  def current_displayed_featured_pictures
    self.pictures.where(:is_deleted => false,:is_feature_picture => true, :is_feature_picture_displayed =>true  ).order("name ASC")
  end


  def publish 
    if self.is_published == false  
      if self.has_ever_been_published == false
        self.has_ever_been_published = true 
        self.first_publication_datetime = DateTime.now  
      end
      self.is_published = true 
    else
      self.is_published = false 
    end
    
    self.save 
    
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:show]
  
  def show
    @project = Project.find params[:id]
    if @project.is_published == false
      redirect_to root_url
      return 
    end
    
    render :layout => "front_page_show"  , :file => 'home/front_page/show'
    
  end
  
  def index
    @projects = Project.latest_available_projects
  end
  
  
  def create 
    @new_object =  Project.create_object( current_user, params[:project])  
  end
  
  def edit_project_content
    @project = Project.find_by_id params[:project_id]
    
    add_breadcrumb "Portfolio", 'projects_url'
    set_breadcrumb_for @project, 'edit_project_content_url' + "(#{@project.id})", 
                "Manage Content"
  end
  
  def update_project_content
    @project = Project.find_by_id params[:project_id]
    puts "***239482398432 total error lengths = #{@project.errors.messages.length }"
    
    
    @project.update_object( current_user, params[:project])
    @has_no_errors  = @project.errors.messages.length == 0 
  end
  
  def manage_featured_project
    @project = Project.find_by_id params[:project_id]
    @new_picture = Picture.new 
    
    @pictures = @project.pictures.where(:is_deleted => false , :is_feature_picture => true ).order("name ASC")
    
    add_breadcrumb "Portfolio", 'projects_url'
    set_breadcrumb_for @project, 'manage_featured_project' + "(#{@project.id})", 
                "Manage Featured Picture"
  end
  
  def publish
    @project = Project.find_by_id params[:entity_switch_id]
    @project.publish
    
  end
  
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_edit_object_form.html.erb
<%= simple_form_for( object , :url => url,
      :method => :post , 
      :html => {:class => "form-vertical prevent_double_submit ajax-form  ",
        :id => "edit_object"}) do |f| %>

  <%= f.input :title  , :input_html => {:class => "input-xlarge span5"}, 
  :label => "Title" %>


  <%= f.input :teaser , :input_html => {:class => "input-xlarge span5", :rows => 5}, 
  :label => "Teaser" %>
  
  <%= f.input :description , :input_html => {:class => "input-xlarge span5", :rows => 5}, 
  :label => "Story" %>
  

  <div class="form-actions">
    <%= f.button :submit , :class => "btn btn-primary", :value=> "Update Project" %> 
  </div>
<% end %>

app/views/projects/_fake_articles.html.erb
<%= render :partial => "projects/fake_articles" %>
<% array = [
  {
    :pic => 'http://cheesenclick.com/wp-content/uploads/2012/06/DSC_0220(pp_w900_h599).jpg',
    :teaser => "Perfection is in the eyes of God."
  },
  {
    :pic => 'http://www.menaralighthouse.com/images/article/000_MG_3455-01.jpg___4GK8r2uRZCAdduhSdEDz.jpg',
    :teaser => "markus+pamela!



    It is a love story between Jakarta and Bandung, Markus lives in Jakarta while Pam in Bandung. here is the interesting story, they almost finished their wedding preparation but suddenly they wanted us to do their prewedding photo. The prewedding itself is a representation of how they have been dating so far. The aeroplane scene was a phase where they did the long-distance relationship. Actually we wanted to do the session in airport, but due to complex bureaucracy we chose another option.



    We can't avoid social media nowadays, neither they did. Markus sent a message via Facebook to Pamela and from there everything was begun. Surprisingly, they still keep the message, we think it is like a souvenir in their relationship. At the day of prewedding session, we need to travel quite far from one place to another, the weather and sunshine were too harsh at afternoon, so we waited around 4 PM and found out dark clouds :O everywhere. We used that situation to accentuate the clouds dramatically! Really love the aeroplane scene...



    Hey lover, keep going!

    "
  },
  {
    :pic => 'http://www.monopictura.com/blog/wp-content/uploads/2012/08/mono-w-sansri-05.jpg',
    :teaser => 'test'
  },
  {
    :pic => 'http://www.foreachlove.com/wp-content/uploads/2012/08/0001.jpg',
    :teaser => 'test'
  }  
]%>


<% array.each do |element| %>
  <article class='row'> 
    <div class='span6'>
      <%= image_tag element[:pic] %>
    </div>
    <div class='span3'>
      <%=  element[:teaser]%>
    </div>
  </article>
<% end %>

app/views/projects/_new_object_form.html.erb
<%= simple_form_for( new_object , :url => url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form   no_content_form",
        :id => "new_object"}) do |f| %>

  <%= f.input :title  , :input_html => {:class => "input-xlarge span5"}, 
  :label => "Title" %>

  <%= f.input :description , :input_html => {:class => "input-xlarge span5", :rows => 5}, 
  :label => "Description" %>

  <div class="form-actions">
    <%= f.button :submit , :class => "btn btn-primary", :value=> "Create Project" %>
    <%= link_to 'Cancel', '#', :class=> "btn btn-danger form_closer"%>
  </div>
<% end %>

app/views/projects/_no_entry_notification.html.erb
<article class='row' id='no_entry_notification'> 
  <div class='span6'>
    <div class="alert alert-error">
      <button data-dismiss="alert" class="close" type="button">×</button>
      <strong>Ouch!</strong> You don't have any images uploaded yet. Why don't you try to upload some? 
    </div>
  </div>
  <div class='span3'>
    <h3>
      No project at all.
    </h3>
    <p>
      What about uploading some pics, nyaaaan?
    </p>
  </div>
</article>

app/views/projects/_object_list_entry.html.erb
<article class='row dashboard_project_entry' id='entry-<%= project.id %>' > 
  <div class='span6' style='overflow:hidden; max-height:500px;'>
  
    <% if project.main_picture.nil? %>
      <%#= image_tag 'upload_images_prompt.jpg' %>
      <div class="alert alert-error">
        <strong>Ouch!</strong> You don't have any pictures uploaded yet. 
        
        <p>
          Why don't you try to 
              <%= link_to "upload some pictures?", 
                      new_project_picture_url(project.id), 
                      :style => "font-weight:bold; color:#e95850;" %>
        </p>
      </div>
    <% else %>
      <%= image_tag project.main_picture.dashboard_image_url %>
    <% end %>
    
  </div>
  <div class='span3'>
    
    <h1><%= project.title %></h1>
    <div class='project-description'>
      <% if project.description.nil? %>
        No description yet. 
      <% else %>
        <%=  project.description[0..150] + "..." %>
      <% end %>
      
    </div>
    

    <ul class="latest-post post-statistic"> 
      <li class="clearfix">
        <%= link_to new_project_picture_url(project.id) do %>
           <%= image_tag BACKEND_IMAGE_URL[:manage_pictures], :style => 'opacity:1 ;'%>
        <% end %>
       
       
        <div style='margin-left:65px;'>
          <%= link_to "Manage Pictures", new_project_picture_url(project.id)  %> 
          <span class="date"><%= project.content_pictures.count %> pictures</span>
          <span class="date"><%= project.current_main_pictures.count %> teaser</span>
        </div>
        
        
        
      </li>
     
      <li class="clearfix">
        
        <%= link_to edit_project_content_url(project.id) do %>
           <%= image_tag BACKEND_IMAGE_URL[:manage_content], :style => 'opacity:1 ;'%>
        <% end %>
        
        <div style='margin-left:65px;'>
          <%= link_to "Manage Content", edit_project_content_url(project.id) %>  
          <span class="date">
            Title: 
            <% if  not project.title.nil? and project.title.length != 0 %>
              <i class="icon-ok-sign" style='background-color: #DFF0D8'></i> 
            <% else %>
              <i class="icon-exclamation-sign"  style='background-color: #F2DEDE'></i> 
            <% end %>
          </span>
          <span class="date">
            Teaser: 
            <% if  not project.teaser.nil? and project.teaser.length != 0 %>
              <i class="icon-ok-sign"  style='background-color: #DFF0D8'></i> 
            <% else %>
              <i class="icon-exclamation-sign"  style='background-color: #F2DEDE'></i> 
            <% end %>
          </span>
          <span class="date">
            Story: 
            <% if  not project.description.nil? and project.description.length != 0 %>
              <i class="icon-ok-sign" style='background-color: #DFF0D8'></i> 
            <% else %>
              <i class="icon-exclamation-sign"  style='background-color: #F2DEDE'></i> 
            <% end %>
          </span>
        </div>
        
        
      </li>
      
      <li class="clearfix">
        
        <%= link_to manage_featured_project_url(project.id) do %>
           <%= image_tag BACKEND_IMAGE_URL[:manage_featured_pictures] , :style => 'opacity:1 ;'%>
        <% end %>
        
        <div style='margin-left:65px;'>
          <%= link_to "Featured Picture", manage_featured_project_url(project.id) %> 
          <span class="date"><%= project.featured_pictures.count %> pictures</span>
          <span class="date"><%= project.current_displayed_featured_pictures.count %> featured</span> 
        </div>
        
      </li>
    </ul>
    
    <br />
    <h4>Publication Status</h4>
    
    <div  id='toggler-<%=  project.id %>' class='project-publish-button toggler'> 
      <% if project.is_published == true %>
        <input type="checkbox" class='toggle-checkbox' checked='checked'>
      <% else %>
        <input type="checkbox" class='toggle-checkbox'>
      <% end %>
    </div>


  </div>
</article>

app/views/projects/create.js.erb
 
$(document).ready(function(){
  var $form = $("#new_object");  
  <% new_form = escape_javascript(  render :partial => "projects/new_object_form", :locals => {
            :new_object => @new_object,
            :url => projects_url 
          }) %>
  
  //  hide showLoading 
  $form.hideLoading();  
  $form.replaceWith('<%= new_form %>');  
  var $form = $("#new_object");  
  
  // show the alert (either success or fail)
  var $form_opener = $("#new_object_opener");
   
  <% if @new_object.persisted? %>  
    $form.hide(); 
    $form.clearForm();  
    
    <% new_row = escape_javascript(  render :partial => "projects/object_list_entry", :locals => { 
              :project => @new_object
            }) %>
          
    $("#project_form_wrapper").after('<%= new_row %>'); 
    $("#no_entry_notification").remove();
    
    $('#toggler-<%=  @new_object.id %>').toggleButtons({ 
       label: {
         enabled: "PUBLISH",
         disabled: "Draft"
       },
       width: 200,
       onChange: function ($el, status, e) {
         executeToggling( $el.parents(".toggler").attr("id") , status ); 
       }
     });
  
  <% else %> 
  
    $form.hideLoading();  
    $form.show(); 
  <% end %>
  
  if( $("#alert").length == 0 ){
    $("#new_object_opener").after('<%= alert %>');
  }else{
    $("#alert").replaceWith('<%= alert %>');
  }
  
  
  
  $(".datepicker").datepicker({
    format: 'dd/mm/yyyy',
    autoclose : true 
  });
  
   
 
  
});

app/views/projects/edit_project_content.html.erb
<%= render :partial => "layouts/dashboard_guide", :locals => {
  :title => "Project",
  :description => "Edit Portfolio Entry Content"
} %> 


<%= create_breadcrumb(@breadcrumbs).html_safe %>


<div class="row">
  <!-- render the page -->
  <!-- START OF THE DASHBOARD PAGE  -->
  <section class="span9 alignright testimonials" id="object_list"> 
   
   <div class='span9' id='project_form_wrapper' style="margin-left:0; margin-bottom:30px;" >
     <div class='row'>
       <div class='span6'>
         <h3 id='form_header'>Project Content</h3>
          <%= render :partial => "projects/edit_object_form", :locals => {
            :object => @project,
            :url => update_project_content_url(@project.id)
          }%>
       </div>
       <div class='span2'>
         <h3 style='text-align:center;'>
           Category 
          </h3>
         <table cellpadding="0" cellspacing="0" border="0" 
               class="table table-striped table-bordered" id="stat" style="margin-top:10px;"> 
             <tbody>
               <tr>
                 <td style='font-weight:bold;'>Prewedding</td>
                 <td  id="selected_counter">0</td>
               </tr>
             
               <tr>
                 <td style='font-weight:bold;'>
                   Wedding
                 </td>
                 <td>
                   <span id="uploaded_counter">0</span>
                 </td>
               </tr>
               
               <tr>
                 <td style='font-weight:bold;'>
                   Family Picture
                 </td>
                 <td>
                   <span id="processed_counter">0</span>
                 </td>
               </tr>
               
               <tr>
                 <td style='font-weight:bold;'>
                   Baby Picture
                 </td>
                 <td>
                   <span id="failed_counter">0</span>
                   
                 </td>
               </tr> 
             </tbody>
         </table> 
       </div>
     </div>
   </div>
 
     
  </section>
  
  <!-- END OF THE DASHBOARD PAGE  -->
  <!-- render the process list -->
  <%= render :partial => 'layouts/process_nav'%>
</div>

app/views/projects/index.html.erb
<%= render :partial => "layouts/dashboard_guide", :locals => {
  :title => "Portfolio",
  :description => "Manage your portfolio to be seen by the public"
} %> 


<div class="row">
  <!-- render the page -->
  <!-- START OF THE DASHBOARD PAGE  -->
  <section class="span9 alignright testimonials" id="object_list"> 
    <div class='span9' id='project_form_wrapper' style="margin-left:0; margin-bottom:30px;" >
      <div id='new_object_opener' > 
        <a class="btn btn-success btn-large form_opener">
          <i class="icon-plus icon-white"></i>
          Create Project
        </a>
      </div>

      <br />

      <%= render :partial => "projects/new_object_form", :locals => {
        :new_object => Project.new,
        :url => projects_url 
      }%> 
    </div>







    <% if @projects.length != 0 %>
      <% @projects.each do |project| %>
        <%= render :partial => "projects/object_list_entry", :locals => {
          :project => project
        } %>
      <% end %> 
    
    <% else %>
      <%= render :partial => "projects/no_entry_notification"  %>
    <% end %>
    
    
    <!--  FAKE article, for starting up --> 
    <%#= render :partial => "projects/fake_articles" %>
    
  </section>
  
  <!-- END OF THE DASHBOARD PAGE  -->
  <!-- render the process list -->
  <%= render :partial => 'layouts/process_nav'%>
</div>


<!-- form to trigger the project publication  -->
<div class=" hidden" id="trigger_switch">
  <%= form_for Picture.new, :url => publish_url   do |f| %>
    <%= hidden_field_tag 'entity_switch_id' , ''  %> 
    <%= hidden_field_tag 'action_value', '' %>
  <% end %>
</div>

app/views/projects/manage_featured_project.html.erb
<%= render :partial => "layouts/dashboard_guide", :locals => {
  :title => "Project",
  :description => "Edit Featured Status and Upload Featured Picture"
} %> 
<%= create_breadcrumb(@breadcrumbs).html_safe %>

 

<div class="row">
  <!-- render the page -->
  <!-- START OF THE DASHBOARD PAGE  -->
  <section class="span9 alignright testimonials" id="object_list"> 
    <div class='span9' id='project_form_wrapper' style="margin-left:0; margin-bottom:30px;" >
      <div id='new_object_opener' > 
        <a class="btn btn-success btn-large form_opener">
          <i class="icon-plus icon-white"></i>
          Upload Picture
        </a>
      </div>

      <br />


      <div class='row'>
        <div class='span6'>
          <div class="alert alert-error">
             <button data-dismiss="alert" class="close" type="button">×</button>
             <strong>Notice:</strong> Upload Picture with width: <b>1600px</b> and height around <b>1000-1100px</b>. If 
             the width is less than 1600 px, it won't look good. 
           </div>
          <%= render :partial => "pictures/uploader/plupload_featured_uploader" %>
        </div>
        <div class='span2 no_content_form'>
          <table cellpadding="0" cellspacing="0" border="0" 
                class="table table-striped table-bordered" id="stat" style="margin-top:10px;"> 
              <tbody>
                <tr>
                  <td style='font-weight:bold;'>Selected</td>
                  <td  id="selected_counter">0</td>
                </tr>
              
                <tr>
                  <td style='font-weight:bold;'>
                    Uploaded
                  </td>
                  <td>
                    <span id="uploaded_counter">0</span>
                  </td>
                </tr>
                
                <tr>
                  <td style='font-weight:bold;'>
                    Resized
                  </td>
                  <td>
                    <span id="processed_counter">0</span>
                  </td>
                </tr>
                
                <tr>
                  <td style='font-weight:bold;'>
                    Failed
                  </td>
                  <td>
                    <span id="failed_counter">0</span>
                    
                  </td>
                </tr> 
              </tbody>
          </table>
          <ul id='fail-list'>
            
          </ul>
        </div>
      </div>
      
      
      
      <% content_for :additional_css do %>
        <%= stylesheet_link_tag "jquery.plupload.queue"%>
      <% end %>
      
      <% content_for :additional_js do %>
        <%= javascript_include_tag "plupload.full", "jquery.plupload.queue", "plupload_transloadit" %>  
      <% end %>
       
      <%#= render :partial => "pictures/inline_js/plupload_featured_js"%>
       
    </div>


    <div>
      
      <% @pictures.each do |picture| %>
          <%= render :partial => 'pictures/featured_entry', :locals => {
            :picture => picture 
          }%>
      <% end %>
      


    </div>
 
     
  </section>
  
  <!-- END OF THE DASHBOARD PAGE  -->
  <!-- render the process list -->
  <%= render :partial => 'layouts/process_nav'%>
</div>



<!-- form to delete picture -->
<div class=" hidden" id="trigger_delete">
  <%= form_for Picture.new, :url => destroy_picture_url   do |f| %>
    <%= hidden_field_tag 'entity_id' , ''  %> 
  <% end %>
</div>


<!-- form to trigger the featured pic -->
<div class=" hidden" id="trigger_switch">
  <%= form_for Picture.new, :url => switch_featured_url   do |f| %>
    <%= hidden_field_tag 'entity_switch_id' , ''  %> 
    <%= hidden_field_tag 'action_value', '' %>
  <% end %>
</div>



 

app/views/projects/publish.js.erb
$(document).ready(function(){ 
  
  
  // the object 
  var $wrapper = $("#entry-<%= @project.id %>");
  $wrapper.hideLoading();  
  
  <% new_row = escape_javascript( render :partial => "projects/object_list_entry", :locals => {
    :project => @project 
  }) %>

  $("#entry-<%= @project.id %>").replaceWith('<%= new_row %>');
  
  $('#toggler-<%=  @project.id %>').toggleButtons({ 
    label: {
      enabled: "PUBLISH",
      disabled: "Draft"
    },
    width: 200,
    onChange: function ($el, status, e) {
      executeToggling( $el.parents(".toggler").attr("id") , status ); 
    }
  });
  
});

app/views/projects/show.html.erb
<%= render :partial => "layouts/dashboard_guide", :locals => {
  :title => "#{@project.title}",
  :description => "#{@project.teaser}"
} %> 
 
 

<div class="row portfolio-single entry" style='margin-bottom:30px;'>

  <!-- .span8 -->
  <div class="span12" style="text-align:center;">
    <div class='image-portfolio-wrapper' style='margin-bottom:30px;'>
      <% @project.content_pictures.each do |picture| %>
        <%= image_tag picture.index_image_url , :style => 'margin-bottom:10px;'%>
      <% end %> 
    </div>
    
    
    <% if not  @project.description.nil?  and @project.description.length != 0 %>
      <div class='project-description'> 
        <%= @project.description %>
      </div>
    <% end %>
    
  </div><!-- /.span8 -->

  
</div><!-- /.row -->  

app/views/projects/update_project_content.js.erb
$(document).ready(function(){
  var $form = $("#edit_object");  
  <% new_form = escape_javascript(  render :partial => "projects/edit_object_form", :locals => {
    :object => @project,
    :url => update_project_content_url(@project.id)
  })%>
  
  //  hide showLoading 
  $form.hideLoading();  
  $form.replaceWith('<%= new_form %>');  
  var $form = $("#edit_object");  
  
  <% if @has_no_errors == true %>
    <% alert = escape_javascript(render :partial => "layouts/alert", :locals => {
      :success => true , 
      :text => "#{@project.title} is successfully updated."
    }) %>
  <% else %>
  <% alert = escape_javascript(render :partial => "layouts/alert", :locals => {
    :success => false , 
    :text => "Project update is not successful."
  }) %>
  <% end %>
  
  if( $("#alert").length == 0 ){
    $("#form_header").after('<%= alert %>');
  }else{
    $("#alert").replaceWith('<%= alert %>');
  }
  
  setTimeout(function(){ 
      removeElementWithID("alert"); 
      }, 3000);
  
  
  
   
   
  
  
});