config/routes.rb
Womo::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'
  match 'dashboard' => "home#dashboard" , :as => :dashboard
  
  resources :projects  do 
    resources :pictures 
  end
  resources :bookmarks 
  
  devise_scope :user do
    get "admin", :to => "devise/sessions#new"
  end
  
  # uploading assembly_url to project  # if the processing is done in the server. 
  match 'create_picture_from_assembly/:project_id' => "pictures#create_picture_from_assembly", :as => :create_picture_from_assembly, :method => :post
  match 'transloadit_status_for_picture' => "pictures#transloadit_status_for_picture", :as => :transloadit_status_for_picture, :method => :post
  match 'new_uploaded_picture_display/:picture_id' => "pictures#new_uploaded_picture_display", :as => :new_uploaded_picture_display
  
  
  
  # edit project content: title, teaser, story/description, :featured status , upload featured image
  match 'edit_project_content/:project_id' => "projects#edit_project_content", :as => :edit_project_content
  match 'update_project_content/:project_id' => "projects#update_project_content", :as => :update_project_content, :method => :post 
  
  # manage featured project ( appears in the front page )
  match 'manage_featured_project/:project_id' => "projects#manage_featured_project", :as => :manage_featured_project
  match 'create_featured_picture/:project_id' => 'pictures#create_featured_picture',  :as => :create_featured_picture, :method => :post 
  
  # picture 
  match 'destroy_picture' => 'pictures#destroy_picture', :as => :destroy_picture, :method => :post 
  match 'switch_teaser' => "pictures#switch_teaser", :as => :switch_teaser, :method => :post 
  
  match 'switch_featured' => "pictures#switch_featured", :as => :switch_featured, :method => :post 
  
  match 'publish' => 'projects#publish', :as => :publish, :method => :post 
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :assembly_url, :is_resizing_completed, :project_id
  belongs_to :project
  
  def Picture.create_from_assembly_url(assembly_url, project)
    pic = Picture.create(:assembly_url => assembly_url, :is_resizing_completed => false , :project_id => project.id)
    
    pic.delay.extract_from_assembly_url
    return pic
  end
  
  def Picture.assembled_pic_id_from( pic_id_list ) 
    Picture.find(:all, :conditions => {
      :id => pic_id_list, 
      :is_resizing_completed => true 
    }).map{|x| x.id }
  end
  
  
  def extract_from_assembly_url
    content = open(self.assembly_url).read
    # json = JSON.parse(content)
    
    
    
    # transloadit_params = ActiveSupport::HashWithIndifferentAccess.new(
    #           ActiveSupport::JSON.decode content
    #         )
    #         
    #     while transloadit_params[:ok] != "ASSEMBLY_COMPLETED"
    #       sleep 2
    #       puts "in the loop"
    #       content = open(self.assembly_url).read
    #       transloadit_params = ActiveSupport::HashWithIndifferentAccess.new(
    #             ActiveSupport::JSON.decode content
    #           )
    #     end
    
    self.parse_transloadit( content , FALSE_CHECK)
    
    
      
  end
  
  def parse_transloadit( params , is_featured_check) 
   
    self.original_image_url  = params['results'][':original']['0']['url'] 
    self.index_image_url     = params['results']['resize_index']['0']['url']    
    self.dashboard_image_url  =  params['results']['resize_dashboard']['0']['url']   
    puts "THe url is done\n"*10 
    
    self.original_image_size = params['results'][':original']['0']['size']  
    self.index_image_size    = params['results']['resize_index']['0']['size']        
    self.dashboard_image_size = params['results']['resize_dashboard']['0']['size']       
    puts "THe image size is done\n"*10
    
    if is_featured_check == TRUE_CHECK
      self.feature_image_url = params['results']['resize_featured']['0']['url']   
      self.feature_image_size = params['results']['resize_featured']['0']['size']    
      
      self.feature_image_thumbnail_url = params['results']['resize_featured_thumbnail']['0']['url']   
      self.feature_image_thumbnail_size = params['results']['resize_featured_thumbnail']['0']['size']   
      self.is_feature_picture = true         
    end
    
    
    puts "Extracting name is done\n"*10
    self.name                =  params['results'][':original']['0']['name']  
    
    if not self.assembly_url.nil?
      self.is_resizing_completed = true
    end
    
    
    
    self.save
  end
  
  def mark_as_deleted
    self.is_deleted = true 
    self.save 
  end
  
  def switch_teaser(value)
    if value.to_i == TRUE_CHECK
      self.other_current_main_pictures.each do |pic|
        pic.is_main_picture = false
        pic.save
      end
      self.is_main_picture = true 
      self.save 
    else
      self.is_main_picture = false
      self.save
    end
  end
  
  def other_current_main_pictures
    current_pic = self 
    self.project.current_main_pictures.where{ id.not_eq current_pic.id }
  end
  
  
  def other_featured_pictures
    current_pic = self 
    self.project.current_displayed_featured_pictures.where{ id.not_eq current_pic.id }
  end
  
  def switch_featured(  value )
    if value.to_i == TRUE_CHECK
      self.other_featured_pictures.each do |pic|
        pic.is_feature_picture_displayed = false
        pic.save
      end
      self.is_feature_picture_displayed = true 
      self.save 
      project = self.project 
      project.is_featured_project = true
      project.save 
    else
      self.is_feature_picture_displayed = false
      self.save
      
      if self.other_featured_pictures.count == 0 
        project = self.project 
        project.is_featured_project = false
        project.save
      end
        
    end
  end
  
  
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
    @project = Project.find_by_id params[:project_id]
    @new_picture = @project.pictures.new 
    @pictures = @project.pictures.where(:is_deleted => false , :is_feature_picture => false ).order("name ASC")
    
    add_breadcrumb "Portfolio", 'projects_url'
    set_breadcrumb_for @project, 'new_project_picture_url' + "(#{@project.id})", 
                "Manage Pictures"
  end
  
  def create_picture_from_assembly
    @project = Project.find_by_id( params[:project_id] )
    assembly_url = params[:assembly_url]
    # ensure_project_membership
    
    @picture = Picture.create_from_assembly_url(assembly_url, @project)
    
    respond_to do |format| 
      format.js do 
        is_completed_result = 0 
        if @picture.is_resizing_completed == true
          is_completed_result= 1
        end
        render :json => {'picture_id' => @picture.id, 'is_completed' => is_completed_result}.to_json  
      end
    end
  end
  
  def transloadit_status_for_picture
    # @picture = Picture.find_by_id( params[:picture_id])
    array_of_assembled_pic_id = Picture.assembled_pic_id_from( params[:non_completed_pic_id_list].split(",").map{|x| x.to_i })
      
    
    
    respond_to do |format| 
      format.js do 
        # is_completed_result = 0 
        # if @picture.is_completed == true
        #   is_completed_result= 1
        # end
        render :json => array_of_assembled_pic_id.to_json  
      end
    end
  end
  
  
  def create
    @project = Project.find_by_id( params[:project_id])
    @picture = Picture.create 
    @picture.project_id = @project.id 
    @picture.save 
      
    @picture.parse_transloadit( params , FALSE_CHECK)
  end
  
  def create_featured_picture
    @project = Project.find_by_id( params[:project_id])
    @picture = Picture.create 
    @picture.project_id = @project.id 
    @picture.save 
     
        
    @picture.parse_transloadit( params , TRUE_CHECK)  
  end
  
  
  def destroy_picture
    @picture = Picture.find_by_id params[:entity_id]
    
    @picture.mark_as_deleted
  end
  
  def switch_teaser
    @picture = Picture.find_by_id params[:entity_switch_id]
    
    @other_current_picture_id_list = @picture.other_current_main_pictures.map{|x| x.id }
    
    @picture.switch_teaser( params[:action_value].to_i )
    @other_current_picture_list = Picture.where(:id => @other_current_picture_id_list) 
  end
  
  def switch_featured
    @picture = Picture.find_by_id params[:entity_switch_id]
    
    @other_displayed_featured_picture_id_list = @picture.other_featured_pictures.map{|x| x.id }
    
    @picture.switch_featured( params[:action_value].to_i )
    @other_displayed_featured_picture_list = Picture.where(:id => @other_displayed_featured_picture_id_list)
  end
  
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_entry.html.erb
<article class='row dashboard_project_entry' id="entry-<%= picture.id %>"> 
  <div class='span6'>
  
      <%= image_tag picture.dashboard_image_url %> 
  </div>
  <div class='span3'>
    
    
    <div class='project-description' style='margin-top:20px;'>
      <%= picture.name %>
    </div>
 
    
        
    
    <br />
    <h4>Teaser?</h4>
    <div  id='toggler-<%=  picture.id %>' class='pic-toggle-button toggler'>
      <% if picture.is_main_picture == true %>
        <input type="checkbox" class='toggle-checkbox' checked='checked'>
      <% else %>
        <input type="checkbox" class='toggle-checkbox'>
      <% end %>
      
    </div>
    
    
    <hr /> 
    <div> 
      <%= link_to destroy_picture_url(picture), :id=>"destroy_entry-#{picture.id}", :class => "btn btn-danger btn-large trigger_delete" do %>
        <i class="icon-remove icon-white"></i>
        Delete
      <% end %>
     
    </div>


  </div>
</article>

app/views/pictures/_featured_entry.html.erb
<article class='row dashboard_project_entry' id="entry-<%= picture.id %>"> 
  <div class='span6'>
  
      <%= image_tag picture.dashboard_image_url %> 
  </div>
  <div class='span3'>
    
    
    <div class='project-description' style='margin-top:20px;'>
      <%= picture.name %>
    </div>
 
    
        
    
    <br />
    <h4>Featured?</h4>
    <div  id='toggler-<%=  picture.id %>' class='pic-toggle-button toggler'>
      <% if picture.is_feature_picture_displayed == true %>
        <input type="checkbox" class='toggle-checkbox' checked='checked'>
      <% else %>
        <input type="checkbox" class='toggle-checkbox'>
      <% end %>
    </div>
    
    
    <hr /> 
    <div> 
      <%= link_to destroy_picture_url(picture), :id=>"destroy_entry-#{picture.id}", :class => "btn btn-danger btn-large trigger_delete" do %>
        <i class="icon-remove icon-white"></i>
        Delete
      <% end %>
     
    </div>


  </div>
</article>

app/views/pictures/create.js.erb
$(document).ready(function(){});

app/views/pictures/create_featured_picture.js.erb
$(document).ready(function(){});

app/views/pictures/destroy_picture.js.erb
$(document).ready(function(){
   $("#entry-<%= @picture.id %>").hideLoading();
   
  <% if @picture.is_deleted == true %> 
    $("#entry-<%= @picture.id %>").remove(); 
  <% end %>
});

app/views/pictures/new.html.erb
<%= render :partial => "layouts/dashboard_guide", :locals => {
  :title => "Picture",
  :description => "Upload/Delete Picture"
} %> 


<%= create_breadcrumb(@breadcrumbs).html_safe %>


<div class="row">
  <!-- render the page -->
  <!-- START OF THE DASHBOARD PAGE  -->
  <section class="span9 alignright testimonials" id="object_list"> 
    <div class='span9' id='project_form_wrapper' style="margin-left:0; margin-bottom:30px;" >
      <div id='new_object_opener' > 
        <a class="btn btn-success btn-large form_opener">
          <i class="icon-plus icon-white"></i>
          Upload Picture
        </a>
      </div>

      <br />


      <div class='row'>
        <div class='span6'>
          <%= render :partial => "pictures/uploader/plupload_uploader" %>
        </div>
        <div class='span2 no_content_form'>
          <table cellpadding="0" cellspacing="0" border="0" 
                class="table table-striped table-bordered" id="stat" style="margin-top:10px;"> 
              <tbody>
                <tr>
                  <td style='font-weight:bold;'>Selected</td>
                  <td  id="selected_counter">0</td>
                </tr>
              
                <tr>
                  <td style='font-weight:bold;'>
                    Uploaded
                  </td>
                  <td>
                    <span id="uploaded_counter">0</span>
                  </td>
                </tr>
                
                <tr>
                  <td style='font-weight:bold;'>
                    Resized
                  </td>
                  <td>
                    <span id="processed_counter">0</span>
                  </td>
                </tr>
                
                <tr>
                  <td style='font-weight:bold;'>
                    Failed
                  </td>
                  <td>
                    <span id="failed_counter">0</span>
                    
                  </td>
                </tr> 
              </tbody>
          </table>
          <ul id='fail-list'>
            
          </ul>
        </div>
      </div>
      
      
      
      <% content_for :additional_css do %>
        <%= stylesheet_link_tag "jquery.plupload.queue"%>
      <% end %>
       
      <% content_for :additional_js do %>
        <%= javascript_include_tag "plupload.full", "jquery.plupload.queue", "plupload_transloadit" %>  
      <% end %>
       
    </div>


    <div>
      
      <% @pictures.each do |picture| %>
          <%= render :partial => 'pictures/entry', :locals => {
            :picture => picture 
          }%>
      <% end %>
      


    </div>

 
     
  </section>
  
  <!-- END OF THE DASHBOARD PAGE  -->
  <!-- render the process list -->
  <%= render :partial => 'layouts/process_nav'%>
</div>

<!-- form to delete picture -->
<div class=" hidden" id="trigger_delete">
  <%= form_for Picture.new, :url => destroy_picture_url   do |f| %>
    <%= hidden_field_tag 'entity_id' , ''  %> 
  <% end %>
</div>


<!-- form to trigger the teaser pic -->
<div class=" hidden" id="trigger_switch">
  <%= form_for Picture.new, :url => switch_teaser_url   do |f| %>
    <%= hidden_field_tag 'entity_switch_id' , ''  %> 
    <%= hidden_field_tag 'action_value', '' %>
  <% end %>
</div>

app/views/pictures/switch_featured.js.erb
$(document).ready(function(){ 
  // refreshing the other
  <% @other_displayed_featured_picture_list.each do |picture| %>
    <% new_row = escape_javascript( render :partial => "pictures/featured_entry", :locals => {
      :picture => picture 
    }) %>

    $("#entry-<%= picture.id %>").replaceWith('<%= new_row %>');
    
    
    $('#toggler-<%=  picture.id %>').toggleButtons({ 
      label: {
        enabled: "YES",
        disabled: "NO"
      },
      width: 150,
      onChange: function ($el, status, e) {  
        executeToggling( $el.parents(".toggler").attr("id"), status ); 
      }
    });
    
    
  <% end %>
  
  // the object 
  var $wrapper = $("#entry-<%=  @picture.id %>");
  $wrapper.hideLoading();  
  
  <% new_row = escape_javascript( render :partial => "pictures/featured_entry", :locals => {
    :picture => @picture 
  }) %>

  $("#entry-<%= @picture.id %>").replaceWith('<%= new_row %>');
  
  $('#toggler-<%=  @picture.id %>').toggleButtons({ 
    label: {
      enabled: "YES",
      disabled: "NO"
    },
    width: 150,
    onChange: function ($el, status, e) {  
      executeToggling( $el.parents(".toggler").attr("id"), status ); 
    }
  });
  
});

app/views/pictures/switch_teaser.js.erb
$(document).ready(function(){ 
  // refreshing the other
  <% @other_current_picture_list.each do |picture| %>
    <% new_row = escape_javascript( render :partial => "pictures/entry", :locals => {
      :picture => picture 
    }) %>

    $("#pic_entry-<%= picture.id %>").replaceWith('<%= new_row %>');
    
    
    $('#toggler-<%=  picture.id %>').toggleButtons({ 
      label: {
        enabled: "YES",
        disabled: "NO"
      },
      width: 150,
      onChange: function ($el, status, e) {  
        executeToggling( $el.parents(".toggler").attr("id"), status ); 
      }
    });
    
    
  <% end %>
  
  // the object 
  var $wrapper = $("#pic_entry-<%=  @picture.id %>");
  $wrapper.hideLoading();  
  
  <% new_row = escape_javascript( render :partial => "pictures/entry", :locals => {
    :picture => @picture 
  }) %>

  $("#pic_entry-<%= @picture.id %>").replaceWith('<%= new_row %>');
  
  $('#toggler-<%=  @picture.id %>').toggleButtons({ 
    label: {
      enabled: "YES",
      disabled: "NO"
    },
    width: 150,
    onChange: function ($el, status, e) {  
      executeToggling( $el.parents(".toggler").attr("id"), status ); 
    }
  });
  
});