config/routes.rb
Womo::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'
  match 'dashboard' => "home#dashboard" , :as => :dashboard
  
  resources :projects  do 
    resources :pictures 
  end
  resources :bookmarks 
  
  devise_scope :user do
    get "admin", :to => "devise/sessions#new"
  end
  
  # uploading assembly_url to project  # if the processing is done in the server. 
  match 'create_picture_from_assembly/:project_id' => "pictures#create_picture_from_assembly", :as => :create_picture_from_assembly, :method => :post
  match 'transloadit_status_for_picture' => "pictures#transloadit_status_for_picture", :as => :transloadit_status_for_picture, :method => :post
  match 'new_uploaded_picture_display/:picture_id' => "pictures#new_uploaded_picture_display", :as => :new_uploaded_picture_display
  
  
  
  # edit project content: title, teaser, story/description, :featured status , upload featured image
  match 'edit_project_content/:project_id' => "projects#edit_project_content", :as => :edit_project_content
  match 'update_project_content/:project_id' => "projects#update_project_content", :as => :update_project_content, :method => :post 
  
  # manage featured project ( appears in the front page )
  match 'manage_featured_project/:project_id' => "projects#manage_featured_project", :as => :manage_featured_project
  match 'create_featured_picture/:project_id' => 'pictures#create_featured_picture',  :as => :create_featured_picture, :method => :post 
  
  # picture 
  match 'destroy_picture' => 'pictures#destroy_picture', :as => :destroy_picture, :method => :post 
  match 'switch_teaser' => "pictures#switch_teaser", :as => :switch_teaser, :method => :post 
  
  match 'switch_featured' => "pictures#switch_featured", :as => :switch_featured, :method => :post 
  
  match 'publish' => 'projects#publish', :as => :publish, :method => :post 
end

app/views/layouts/header/_logo.html.erb
<!-- .span3.logo -->
<div class="span3 logo">
    <a href="./index.html" >
      .
      <!-- <img src="images/logo.png" alt="Logo" /> -->
    </a>
</div><!-- /.span3.logo -->

app/views/layouts/header/_main_nav.html.erb
<!-- .span9 -->
<nav class="span9">

    <!-- #menu -->
    <ul id="menu">
      <% if current_user %>
        <li>  
            <%= link_to "Dashboard", dashboard_url , :class => "current" %>   
        </li>
      <% end %>
      
      
        <li>
          <%= link_to "Home", root_url , :class => "current" %> 
        </li>
        <li><a href="./about.html" >Fresh</a> 
        </li>
        <!-- <li><a href="./portfolio.html" class="current" data-description="Portfolio Page">Portfolio</a>
                  <ul>
                      <li><a href="./portfolio-left.html">Portfolio Left Sidebar</a></li>
                      <li><a href="./portfolio-right.html">Portfolio Right Sidebar</a></li>
                      <li><a href="./portfolio-single-left.html">Portfolio Single Left</a></li>
                      <li><a href="./portfolio-single-right.html">Portfolio Single Right</a></li>
                  </ul>
              </li> -->
        <li><a href="./blog-left.html" >Explore</a> 
        </li>
    
        <li>
          <% if  current_user %> 
            <%= link_to "Logout", destroy_user_session_url %> 
          <% else %>
            <%= link_to "Login", new_user_session_url %>  
          <% end %>
        </li>
    </ul><!-- /#menu -->

</nav><!-- .span9-->